### ISSUE TITLE
Show posts (events) based on todays date or greater?

### ISSUE THREAD

**Issue by sigersmit** [RTO-Websites/dynamic-conditions#1]
Hi,
Love this plugin, makes elementor almost complete.. Is it possible to filter posts with a custom date field (e.g. start date event) only with date today and greater then today? And if yes, how to do that?
Thank you!

**Comment by crazypsycho** [comment]
Hello,
this plugin is used to show/hide widgets or sections, not for posts.
I recommend Post-Expirator for this.
https://de.wordpress.org/plugins/post-expirator/

But a time-switch is a great idea, also for widgets/sections. We will think about how to implement such a feature.

Thank you!

**Comment by Enoray** [comment]
We are happy to announce that we are working on a solution now. Soon there will be more options to work with times and dates.

**Comment by crazypsycho** [comment]
Hello,
new date-compare options are now included in the new release.

Thank you!
