### ISSUE TITLE
Elementor Forms with RTO  Dynamic Conditions Plugin

### ISSUE THREAD

**Issue by acornavi** [RTO-Websites/dynamic-conditions#10]
HI,
is it possible to make use of this plugin in Elementor Forms? That would be really awesome. 

Thanks for all the good work you did.

**Comment by Enoray** [comment]
Hello,

we have not found any way to add our logic to the Elementor repeater. Elementor forms and many other widgets are using repeater.

So right now we do not know how to implement this feature. If someone got an idea we are open for PRs.
