### ISSUE TITLE
Multiple conditions

### ISSUE THREAD

**Issue by giordanovi** [RTO-Websites/dynamic-conditions#11]
HI,
is it possible to make use of multiple conditions maybe using repeater fields? That would be really awesome.

Thanks for all the good work you did.

**Comment by Enoray** [comment]
Hello @giordanovi,

right now it is not planned to implement multiple conditions. In the most cases you can archive what you want with custom dynamic tags.

Thank you for your Feedback.

**Comment by realstephenzhao** [comment]
Recently I have a similar problem, actually I have to recreate many templates without this multi condition feature.
