### ISSUE TITLE
Possible to list multi values in Conditional value field when Condition is Contains or Does not contain?

### ISSUE THREAD

**Issue by realstephenzhao** [RTO-Websites/dynamic-conditions#15]
Is it possible to list multi values in **Conditional value** field when **Condition** is _Contains_ or _Does not contain_?

I mean to activate this function(hide or show) when **Dynamic Tag** meets each of them in **Conditional value** field, not match all of them.

See screenshot below:

![Dynamic Conditions for Elementor](https://i.imgur.com/bPp8t1k.png)

**Comment by Enoray** [comment]
Hello @realstephenzhao,

in our next update [1.4](https://github.com/RTO-Websites/dynamic-conditions/tree/dev/trunk) there will be an option for arrays. 

If u can not wait, you could try already the version [here](https://github.com/RTO-Websites/dynamic-conditions/tree/dev/trunk)

**Comment by realstephenzhao** [comment]
Thanks very much for your work, I‘ll wait for the official update on wordpress.org.
