### ISSUE TITLE
crash wordpress with version 1.4

### ISSUE THREAD

**Issue by wpcoaching** [RTO-Websites/dynamic-conditions#16]
Cannot use plugin 1.4 because serious problems.

Een fout van het type E_ERROR werd veroorzaakt op regelnummer 69 van het bestand /home/deb50017n2/domains/hervormdaalsmeer.nl/public_html/wp-content/plugins/dynamicconditions/dynamic-conditions.php. Foutmelding: Uncaught Error: Class 'DynamicConditions\Lib\DynamicConditions' not found in /home/deb50017n2/domains/hervormdaalsmeer.nl/public_html/wp-content/plugins/dynamicconditions/dynamic-conditions.php:69
Stack trace:
#0 /home/deb50017n2/domains/hervormdaalsmeer.nl/public_html/wp-settings.php(362): include_once()
#1 /home/deb50017n2/domains/hervormdaalsmeer.nl/public_html/wp-config.php(91): require_once('/home/deb50017n...')
#2 /home/deb50017n2/domains/hervormdaalsmeer.nl/public_html/wp-load.php(37): require_once('/home/deb50017n...')
#3 /home/deb50017n2/domains/hervormdaalsmeer.nl/public_html/wp-admin/admin-ajax.php(22): require_once('/home/deb50017n...')
#4 {main}
  thrown

**Comment by crazypsycho** [comment]
Hello,

we are looking at it, but at the momant we can´t reproduce this issue. 
Possibly something goes wrong on the updating-process. You could try to delete and reinstall the plugin.

Did you have access to the file-system of your server?
Can you look in /public_html/wp-content/plugins/dynamicconditions and say if the folders Public, Lib and Admin are lowercase?

**Comment by wpcoaching** [comment]
Files were lowercase. 
After delete and reinstall no problem.
So I close.

**Comment by wpcoaching** [comment]
Thanks for quick answer,

 

Looked first for lowercase. That is was.

So tried delete and reinstall.

Till now it works.

 

So for the moment happy, because we need the acf functions of your plugin to display some things correct.

 

 

 

Van: crazypsycho <notifications@github.com> 
Verzonden: donderdag 5 september 2019 14:16
Aan: RTO-Websites/dynamic-conditions <dynamic-conditions@noreply.github.com>
CC: wpcoaching <info@wpcoaching.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [RTO-Websites/dynamic-conditions] crash wordpress with version 1.4 (#16)

 

Hello,

we are looking at it, but at the momant we can´t reproduce this issue.
Possibly something goes wrong on the updating-process. You could try to delete and reinstall the plugin.

Did you have access to the file-system of your server?
Can you look in /public_html/wp-content/plugins/dynamicconditions and say if the folders Public, Lib and Admin are lowercase?
