### ISSUE TITLE
Compare Custom Post Type Date field with current date

### ISSUE THREAD

**Issue by sideskift** [RTO-Websites/dynamic-conditions#18]
Hi.

First of all this plugin is great. When I get more time I will contribute to it. Right now I need to know if it could be made possible to compare a custom date field with current date. 

The dynamic source would be the custom field.

The Comparison will be Date, and the compared value would be some way to enter current_date or current_date_time.

So the both values are dynamic.

Right now it is only possible to compare a cusum date field with a fixed date, but having current_date or current_date_time, would make it possible to create new sorts of conditions that are based upon the current date/time. 

Thanks for your great work.

Henrik

**Comment by crazypsycho** [comment]
Hi,

this is already possible. Just select String to time as condition type.
Than you can enter time strings as conditional value like "today", "now", "yesterday" or something like "2019-10-31 +1 month"
It is using the php-function strtotime. Here you can find some examples:
https://www.php.net/manual/en/function.strtotime.php

**Comment by sideskift** [comment]
This is actualy cool, however using now does not work for me. I use a toolset date field. This is configured in toolset to be dateTime, but the debug feature (which is excellent) shows that the Dynamic-Tag-Value is always a date (time is 00.00).

I don't know if its a DynamicCondition thing. It might just as well be an elementor / toolset integration thing?

**Comment by sideskift** [comment]
Well there is a solution. I can simply use a toolset types shortcode and compare that to the strtotime feature with the now value

[types field='fieldslug' output='raw'][/types] will return the time in unix format. So this excellent plugin handles it pretty well :-)

**Comment by supriyaskhire** [comment]
Using 'now' does not work for me. I am using Elementor and PODS plugin's date field for the event date. 
How can I display only upcoming events?
