### ISSUE TITLE
ACF link

### ISSUE THREAD

**Issue by Picpool** [RTO-Websites/dynamic-conditions#2]
Hello,

I set an ELEMENTOR button with ACF link and i want to show this button only if ACF link is not empty.
The problem is that when in your dynamic panel settings i see all my ACF fields but not my ACF link.
Thanks

**Comment by crazypsycho** [comment]
Hello,

ACF link is an URL-Field, so you have to choose ACF-Url-Field instead of ACF-Field. Than you should see your Field.

![ACF-Url-Field](https://cdn.rto.de/img/acf-url-field.png)

Thank you and best regards,
rtowebsites

**Comment by Picpool** [comment]
OH sorry, you are right , it works thanks a lot !!
