### ISSUE TITLE
Ajax support

### ISSUE THREAD

**Issue by tiagoefreitas** [RTO-Websites/dynamic-conditions#21]
Does it support ajax?

I wanted to hide facetwp results when there are no filters activated, or then a specific filter is not used.

I would create a custom dynamic tag that tells if there are active filters, but the filters use ajax, so would visibility also get called and hide/show the element without a page reload?

**Comment by Enoray** [comment]
I don't think that dynamic tags can support ajax. Our Plugin just use the standard Elementor rendering. Without page reload it won't work. I think you'll need an individual Plugin with js for it.
