### ISSUE TITLE
Compare using dyanamic values

### ISSUE THREAD

**Issue by sagarprasai** [RTO-Websites/dynamic-conditions#25]
Hello, First of all thank you making this awesome plugin.
I have a quick question.
Can we compare the dynamic tag with dynamic values.
For example In a event archive page, I want to show if this event is upcoming, ongoing or past based on the a custom field, event_start_date and event_end_date. For these three conditions, I will have to compare one of those customs fields with today's date. Now you have the options to compare date but not, dynamic date, its just date choosing manually.
So is there any options? I think strtodate can be used, but I dont know the exact syntax that will do in the textbox. Can you please help me to solve this?

**Comment by crazypsycho** [comment]
Hello @sagarprasai 

you can use strtodate and have just to enter "today" in the text-field.

**Comment by sagarprasai** [comment]
Thank you. This works for I guess for Upcoming Events (where start_date >today,) and Past Events (enddate<today). But for ongoing events, we need to compare two dynamic dates. Is that possible?

**Comment by crazypsycho** [comment]
I think you could compare it if, you select Date-Today as DynamicTag, use Between as condition and work with shortcode for the event-fields.
If you use ACF, the shortcode looks like this:
`[acf field="start_date"]`
