### ISSUE TITLE
Cannot use dynamic condition with ACF Gallery Field

### ISSUE THREAD

**Issue by artifex-media** [RTO-Websites/dynamic-conditions#29]
It seems I cannot use the Dynamic Condition correctly on ACF Gallery Field’s, even though it is listed in the tags.

- I cannot set an element to hide IF the Gallery Field = empty. It will always hide no matter what.
- I cannot set an element to show IF the Gallery Field != empty. It will always hide no matter what.
- I cannot set an element to hide IF the Gallery Field contains less than X images with the ‘Less Than’ operator. It will always hide.
- I cannot set an element to show IF the Gallery Field contains more than X images with the ‘Greater Than’ operator. It will always hide.

Basicly the conclusion is that this plugin is not compatible with the Gallery Field.
Is this something that can be fixed?

**Comment by crazypsycho** [comment]
Hello,

we just tested the gallery-field. We can´t reproduce your issue with empty/not-empty.
Can you activate debug-mode and copy the content of the debug-box?

Less/Greater than compares the length of the image-urls, and not the count of the images.
We will check if we can implement a count-check.
