### ISSUE TITLE
The Widget is not Completely Hidden, Elementor Wrapper is Still There

### ISSUE THREAD

**Issue by black-eye** [RTO-Websites/dynamic-conditions#3]
Just installed the plugin and from what I've tried it seems that the widget itself is correctly not output to html (leaving only  instead), but the Elementor wrapper is still there

E.G.:
```
<div data-id="7c5b56b" class="elementor-element elementor-element-7c5b56b elementor-widget elementor-widget-text-editor" data-element_type="text-editor.default">
    <div class="elementor-widget-container">
	<!-- hidden widget -->
    </div>
</div>
```
Is it possible to hide the wrapper too?

**Comment by crazypsycho** [comment]
Hello,

you are right, currently only widget content is cleared. I´m with you, that this is not an ideal solution.
I think we can fix this with next version.

For now, you can go to dynamicconditions/lib/DynamicConditions.php
On Line 157 you should find this:
```php
        // filter widgets
        $this->loader->addAction( 'elementor/widget/render_content', $pluginPublic, 'filterWidgetContent', 10, 2 );
```

Just replace with
```php
        // filter widgets
        $this->loader->addAction( "elementor/frontend/widget/before_render", $pluginPublic, 'filterSectionContentBefore', 10, 1 );
        $this->loader->addAction( "elementor/frontend/widget/after_render", $pluginPublic, 'filterSectionContentAfter', 10, 1 );
```

**Comment by black-eye** [comment]
@crazypsycho Excelent, works like charm! Thanks for really quick reply.
In fact, I expected it to be a problem outside the plugin's scope, so it wouldn't be possible to solve. So, its really good news it could be done quite easilly.
I'm just a bit surpriced, I'm the first one who has requested this feature. ;)

**Comment by crazypsycho** [comment]
The fix is now included in the new release.
