### ISSUE TITLE
WP_User->id is deprecated

### ISSUE THREAD

**Issue by WeAreHaus** [RTO-Websites/dynamic-conditions#30]
Hi, 

with Dynamic Conditions activated I get 36 rows in my error_log just by visiting wp-admin or any public page.

`Thu Mar 12 11:23:00.698430 2020] [php7:notice] [pid 56033] [client 127.0.0.1:58746] PHP Notice:  WP_User->id was called with an argument that has been deprecated since version 2.1.0! Use <code>WP_User->ID</code> instead. in /xxx/xxx/web/wp/wp-includes/functions.php on line 4865, referer: http://sitename.whatever/`

The error comes from Elementor PRO, modules/dynamic_tags/tags/user-info.php row ~51, in the switch/case for display_name where $type is id where it should be ID.

This does not happen with Dynamic Conditions deactivated.

Running latest versions of everything on PHP7.3.

**Comment by crazypsycho** [comment]
Hi @WeAreHaus 

i think this is an issue in elementor pro itself. It occours if you select "user info" somewhere as dynamic tag and use ID as field.
But i have a workaround for this. Don´t use ID as field, use meta and enter ID as meta-key, like this:

![grafik](https://user-images.githubusercontent.com/12948745/76527466-90b2b600-646f-11ea-9c4a-80dd4d528180.png)

**Comment by WeAreHaus** [comment]
Tested, works perfectly. Thanks!
