### ISSUE TITLE
in Array hiding parent page

### ISSUE THREAD

**Issue by danmaby** [RTO-Websites/dynamic-conditions#36]
Hi, we're seeing an issue with `in array` hiding the parent page when adding the child page to the array.  For example: if we apply a condition to hide a widget based on `Post URL` and add `example.com/volunteer/apply` in the array box like so: 

![Screenshot 2020-04-28 09 52 37](https://user-images.githubusercontent.com/13104185/80467785-3b0a6e00-8936-11ea-9151-452409f67ff7.jpg)

It then applies the condition to the parent page too i.e. `example.com/volunteer` as you can see here: 

![Screenshot-2020-04-28-09 36 52](https://user-images.githubusercontent.com/13104185/80467896-668d5880-8936-11ea-8a97-d25f04368d65.jpg)

Is this intentional behaviour?  How can we apply an array to the child page only?  

Thanks in advance.

**Comment by crazypsycho** [comment]
Hello,

is the condition in a loop (Like in a post-widget)? When you are in a loop the Post-URL-Tag will output the Url to the Post and not the Url of current page.
It seems that Elementor doesn´t provide a tag to get the current url. But we are planning to develop another plugin which will provide some usefull dynamic tags. But currently we can´t say when this will be released.

**Comment by crazypsycho** [comment]
Other way could be to install a plugin for php-shortcode, than you can use php in your condition an check for the referer.
Something like this:
https://de.wordpress.org/plugins/insert-php-code-snippet/

Than create a shortcode with this:

<?php
echo $_SERVER['REQUEST_URI'];
?>

Than you can select Shortcode as tag in dynamic-conditions and enter the shortcode.
The Shortcode should output "/volunteer/"
