### ISSUE TITLE
Display a widget on certain archive pages

### ISSUE THREAD

**Issue by ardelmedia** [RTO-Websites/dynamic-conditions#37]
Hi there. 

I have a general Archive template in Elementor. I would like a widget to display on only one taxonomy term archive. Is this possible please, and if so how?

Many thanks,
Andrew.

**Comment by crazypsycho** [comment]
Hello,

you could use post terms as dynamic tag for that.

**Comment by ardelmedia** [comment]
-- Please reply above this line --

Thanks so much for contacting Ardel Media.

The office is closed for a couple of days, and we will return on 27
July 2020.
 
We are grateful for your patience and will be back in touch as soon as
possible on our return. 

Thanks again for contacting us. 

Ardel Media Ltd.

Ardel Media Limited is a company registered in England (company
number 09518001).
Registered address:  Ardel Media Ltd, c/o Switch Accountants, Unit
21, City West Business Park, Meadowfield, Co Durham, DH7 8ER, England.

--- End of message.

**Comment by ardelmedia** [comment]
-- Please reply above this line --

Thanks so much for contacting Ardel Media Ltd.

The office is now closed for our Easter break and we will return on
12 April 2021. 

We are grateful for your patience and will be back in touch as soon as
possible on our return. 

If your message is an  absolute emergency then you can email
***@***.*** [1]. Please do not abuse this service - it is
provided on trust and we will only respond to a truly genuine
emergency request. All other messages we will of course respond to
promptly from 12 April 2021, when our usual swift replies will
resume.  

We ask that you respect our holiday period.

Thanks again for contacting us. 

Andrew ">Ardel Media Limited is a company registered in England
(company number 09518001).
Registered address:  Ardel Media Ltd, c/o Switch Accountants, Unit
21, City West Business Park, Meadowfield, Co Durham, DH7 8ER, England.

--- End of message.

Links:
------
[1] ***@***.***
