### ISSUE TITLE
Different CPT with same custom fields names

### ISSUE THREAD

**Issue by PistonPL** [RTO-Websites/dynamic-conditions#38]
Different CPT with same custom fields names are not compared correctly. Only field name is taken in account, no matter with CPT it is attached to.

ie:
![image](https://user-images.githubusercontent.com/6260857/87379064-a8ba5380-c58f-11ea-86e3-31237cea73df.png)

1,2,3 are from different CPT, but filed name is the same for all of them. Condition ( show when field FROM specific CPT is = something ) is meet only for one of them, rest should be hidden.

**Comment by PistonPL** [comment]
![image](https://user-images.githubusercontent.com/6260857/87385167-b971c600-c59d-11ea-99a0-6e43162225f4.png)

**Comment by crazypsycho** [comment]
Hello,

That seems to be a problem with ACF or Elementor itself, since the problem also occurs without DynamicConditions.

The easiest way is to give the fields other names (the label can remain the same).
