### ISSUE TITLE
Show element only if current post has children

### ISSUE THREAD

**Issue by globdug** [RTO-Websites/dynamic-conditions#39]
Hello,
is there a way to show an element only if current post has children?

I would like to show a menu of child pages only if current post has children.

I created a little shortcode that load child pages 

```php
function list_child_pages(){
	global $post;
	$childpages = wp_list_pages([
		'post_type' => $post->post_type,
		'echo' => false,
		'child_of' => $post->ID,
	]);
	$list = '<ul>' . $childpages . '</ul>';
	return $list;
}
add_shortcode('child_pages', 'list_child_pages' );
```

I would like to manage the condition with Dynamic Conditions plugin, not via php. Is it possible?

**Comment by crazypsycho** [comment]
Hello @globdug 

you could select Shortcode as dynamic-tag and enter your shortcode, than check if it contains `<li`.

![grafik](https://user-images.githubusercontent.com/12948745/91287688-5aa08e80-e790-11ea-8535-1a103258dc42.png)

**Comment by globdug** [comment]
Thank you!

While I was waiting for a reply, I solved in a similar way. :)

I have changed the return of function in this way:
```php
if( $childpages=='' ){
	return '';
}else{
	return '<ul>' . $childpages . '</ul>';
}
```

And in DC I set the condition to "Is not empty".

There could be some issues if I use this approach in your opinion or is better yours?

**Comment by crazypsycho** [comment]
I don't think it makes a big difference.
It's more a matter of taste how to do it.

**Comment by globdug** [comment]
Ok, thank you very much for your help and time!
