### ISSUE TITLE
Messed up when shown

### ISSUE THREAD

**Issue by fpolli** [RTO-Websites/dynamic-conditions#40]
I have a widget that is hidden on tablet and mobile (in Elementor), but shown on desktop, and I used the dynamic conditions plugin to only show it when User ID is empty. When it is shown, it is under the widget above it on the page.

I have the same widget in a sidebar as the top widget, with another widget below it. When the conditional widget is shown, it is directly under the widget that should be behind it. The two widgets end up stacked right on top of each other.

https://hoosplace.dream.press/about

The widget hides just fine for logged in users.

**Comment by crazypsycho** [comment]
Hello,

very sorry for the late answer. But your website seems to be offline, so i will close this. Feel free to reopen.
