### ISSUE TITLE
Set dynamic condition based on whether posts are returned or not

### ISSUE THREAD

**Issue by XVII** [RTO-Websites/dynamic-conditions#43]
I have some custom Query ID's which are used to display posts.

I would like to dynamically hide a section based on whether that Query ID returned any posts or not.
![image](https://user-images.githubusercontent.com/446329/108158030-2eab0800-7138-11eb-89ff-b3abbcaea6a7.png)

There is multiple of these queries per page though, so the filtering would need to be able to specify the Query ID and know to only check the results of that query.

I imagine an extension to this tag would be the most effective.

![image](https://user-images.githubusercontent.com/446329/108158095-54d0a800-7138-11eb-87bc-cbb555a27bd0.png)

**Comment by crazypsycho** [comment]
Hello @ShadowXVII 

this seems to be a nice idea. We will check if it is possible to use the query from an id.

**Comment by ShadowXVII** [comment]
Sweet, that would help be either hide a section if it's empty, or potentially put a "No results" message rather than just a blank space.

**Comment by steveindzine** [comment]
+1 for this feature

**Comment by crazypsycho** [comment]
I am sorry to say, but this is not for what elementor has developed the query-id.
The query is not saved under this id, so i cannot access it in the dynamic-tag.

Maybe you can use https://wordpress.org/plugins/dynamictags/ with the widget-content-tag and check if the widget contains posts.
