### ISSUE TITLE
Compare with todays date

### ISSUE THREAD

**Issue by IrishDesigner** [RTO-Websites/dynamic-conditions#44]
I am trying to automate a section and to do so need to compare the date set in an acf custom field with the current date-time (if the event is in the future it will display 'future events' and hide 'past events', otherwise it will display 'past event' and hide 'future events').

Not quite sure how to get the date selector to automatically take todays date/datetime, or is this not currently something the dynamic-conditions can do?

Many thanks in advance for this wonderful plugin,

Michael

**Comment by crazypsycho** [comment]
Hello @IrishDesigner 

i think you could use strtotime as compare type and enter "now" as dynamic value.
Should look like this

![grafik](https://user-images.githubusercontent.com/12948745/113335150-d6654980-9324-11eb-8cc2-0ae5ac04dec0.png)
