### ISSUE TITLE
Hide a whole div based on device

### ISSUE THREAD

**Issue by Lagiulsss** [RTO-Websites/dynamic-conditions#47]
Hi guys!

Is it possibile to hide/show a whole div based on screen size?
How can I select the current div?

I know I could do it directy with Elementor in "Responsive" but this doesn't hide the code in the DOM

Thank you!

**Comment by crazypsycho** [comment]
Hello,

That is not possible with our plugin, because it works server-side and on server-side we didnt have the resolution.
