### ISSUE TITLE
ACF fields not showing up

### ISSUE THREAD

**Issue by IrishDesigner** [RTO-Websites/dynamic-conditions#49]
I am using ACF  to create forms so that certain fields only appear if particular conditions are met, but I cannot get these fields to show up ... this way clients only end up populating the required fields as they add new content to their CPTs.

Is this because Elementor doesn't support field groups? Is this something that could be supported in the future?

I was wondering if there is a way of having a ACF field that allows us to specify which field in particular we are looking for results in by typing in the ACF field name (e.g my_custom_url) and then specifying the type of that field (url)?

Thanks in advance!

**Comment by crazypsycho** [comment]
The tags are provided by elementor pro itself. They have acf-fields, but no acf-group.
