### ISSUE TITLE
Doesn't work using URL condition?

### ISSUE THREAD

**Issue by Thiagobhmg** [RTO-Websites/dynamic-conditions#51]
Hello first I would like to thank you for the plugin!

I did some testing, and I would like to hide a page element if the site URL has a parameter. I tried all available options and it doesn't work.

I would like to hide a button if the site URL has **?tipo=mensal**

**Comment by crazypsycho** [comment]
Sorry for the very late answer, but we can only do support for technical issues and bugs.
But IU think you need some more dynamic-tags.
You could use
https://de.wordpress.org/plugins/dynamictags/
Than you have "current url" as tag available.
