### ISSUE TITLE
Add "context" option to the Number Posts Dynamic Tag -- i.e. Current, Child, Parent

### ISSUE THREAD

**Issue by ShadowXVII** [RTO-Websites/dynamic-conditions#52]
The Number Posts dynamic tag will only return results in context to the current post.
Having counts of child posts, or parent posts, or siblings' posts would also be useful for conditions.

The conditions would be adjusted https://github.com/RTO-Websites/dynamic-conditions/blob/28289be8ba01df35d94f6cbae1739ea6c3a3f392/trunk/Lib/DynamicTags/NumberPostsTag.php#L79-L85

If context is:

- **Current Post** (default): Leave the query as-is -- no extra parameters on query
- **Child**: Add `'child_of' => get_the_ID(),` to the query
- **Parent**: Add `'parent' => get_the_ID(),` to the query
- **Siblings**: Add `'child_of' => wp_get_post_parent_id(),` to the query

**Comment by crazypsycho** [comment]
This tag isnt developed anymore and is only delivered for compatibility.
But in our other plugin
https://de.wordpress.org/plugins/dynamictags/
we provide the "number posts query" tag, with more options, also for custom queries.
