### ISSUE TITLE
Date comparision issue

### ISSUE THREAD

**Issue by qwik3r** [RTO-Websites/dynamic-conditions#57]
Asking this question here since it seems that the Wordpress forum has been abandoned. 

I'm having trouble with hiding something based on a date condition. 

I have configured it so that it should hide a block if the date is greater than the current date: https://share.getcloudapp.com/Wnuybp2K -- however it is not doing it. 

The debug info shows both dates: https://share.getcloudapp.com/bLuKjZXZ

Should it not be hiding it if the date is greater than 3-22-22? 

Any help would be appreciated, thanks.

**Comment by crazypsycho** [comment]
The condition in the image is "hide if less".
