### ISSUE TITLE
Container compatibility

### ISSUE THREAD

**Issue by Critical94** [RTO-Websites/dynamic-conditions#60]
It would be great if the plugin would be compatible with the new Elementor containers. As written on Wordpress forum, otherwise the plugin is no longer usable for a lot of people.

**Comment by crazypsycho** [comment]
Hello @Critical94 

this is already planned. But we can´t say at the moment when we can release this feature.

**Comment by Critical94** [comment]
Nice! Thanks for your fast response and efforts.

**Comment by crazypsycho** [comment]
This is now implemented.
