### ISSUE TITLE
Elementor Icon List Bug

### ISSUE THREAD

**Issue by tobsey85** [RTO-Websites/dynamic-conditions#62]
Hey guys!

First, let me thank you for that great plugin.
It works nicely, but i recognized that after
installing, all my icon list widgets became
a "ul" with a dotted list-style-option.

Could you please fix that?

Big Hugs
Chriss

**Comment by PedroTiagoSimao** [comment]
Hi all,

Yes this is a bug.
If we add multiple Icon Lists, the bug occours when an Icon List is hidden, except if it the last on the DOM.

**No condition met**
![ss1000](https://user-images.githubusercontent.com/5888256/228217707-b9253b9a-98e2-41c4-99cc-558aa896db7b.png)




**Condition met on the 1st Icon List**
![ss2000](https://user-images.githubusercontent.com/5888256/228217738-82f04619-ec5d-49a3-a2ff-24421134bab3.png)




**Condition met on the last Icon List**
![ss30000](https://user-images.githubusercontent.com/5888256/228218161-722f6b73-bba2-4e73-abb8-79c78a01d8f2.png)


Cheers!

**Comment by crazypsycho** [comment]
This is because elementor seems to embed inline <link> for css in the first of the list, which is also removed.
But I will add a fix for that in next version coming soon
