### ISSUE TITLE
Content Tag not working as expected

### ISSUE THREAD

**Issue by fabriciopatron** [RTO-Websites/dynamic-conditions#63]
Hey!

We have imported every product on our store to Woocommerce and would like to hide the Description column when there’s no description.

Technically some of our products are not empty because the woocommerce-product-content-tag shows this as value “<span> </span>” so we can’t ask it to hide when it’s empty. We tried equal to “<span> </span>” but that doesn’t work either.

How would we go about hiding those products? We’ve tried many options but nothing seems to work.

https://www.dropbox.com/s/nxb4ip44iaybwof/tag-wo.png?dl=0

Thanks!

**Comment by crazypsycho** [comment]
Sorry for the late answer. Maybe you can activate develop-mode and see what the tags shows in raw.
Maybe it contains some invisible html-code.
You can also try "less than". On strings this will compare the string-length.
