### ISSUE TITLE
Not working with Elementor 3.8/Jet Engine Listing Grid

### ISSUE THREAD

**Issue by tombauer** [RTO-Websites/dynamic-conditions#64]
I use Dynamic Conditions in a Crocoblock Jet Engine Listing Grid widget. After the Update to Elementor 3.8 it stops working and does not show the content anymore. Is there a general problem regarding Elementor 3.8 or only in combination with the  Listing Grid? Thank you for your advice.

**Comment by crazypsycho** [comment]
Hello @tombauer 

currently we see no general problem with Elementor 3.8. So it seems that is only in combination with the widget.
Can you enable the debug-mode and show what the debug-box outputs?

**Comment by tombauer** [comment]
Dear @crazypsycho 
Thank you for your response. I did again the newest Updates and now - with the newest Version of JetEngine (maybe there was a bug in this plugin...) - everything is working fine. Thanks a lot for your help and a nice day.
