### ISSUE TITLE
Deprecated hook: dynamic_tags/register_tags --> Instead: dynamic_tags/register

### ISSUE THREAD

**Issue by casinojeffrey** [RTO-Websites/dynamic-conditions#65]
File:
DynamicConditions.php:197

Proof:
https://developers.elementor.com/v3-5-planned-deprecations/

**Comment by torchsmith** [comment]
+1

**Comment by TOAD-Joey** [comment]
I created a pull request for this issue; https://github.com/RTO-Websites/dynamic-conditions/pull/66

You can get the file here for now: 
https://github.com/RTO-Websites/dynamic-conditions/blob/494a39ed3d762a3fcebff06b70490d1186cb4041/trunk/Lib/DynamicConditions.php

**Comment by crazypsycho** [comment]
implemented, thanks
