### ISSUE TITLE
PHP 8 and more?

### ISSUE THREAD

**Issue by profesoryeow** [RTO-Websites/dynamic-conditions#69]
Hello. I having problems with PHP 8/8.1/8.2, but 7.4 I don't have problems.
**Do you have maintenance plans for PHP versions 8 or later?**
I hope so, yes, it's the best add-on of its kind I've found, it's straightforward and doesn't come with meaningless extra features.
**Thanks!**

**Comment by crazypsycho** [comment]
Hello,

we are using the plugin on our own websites with PHP 8.2 and dont have problems.
Can we have more details?

**Comment by profesoryeow** [comment]
Sorry, it was my fault.

I was on PHP 7.4, with elementor 3.15.3, in conjunction with elementor pro 3.14.1 and then when I wanted to upgrade to PHP 8.0, PHP 8.1 and PHP 8.2 it generates a problem that throws printed error. Everything is solved by upgrading to the latest version of elementor and elementor pro.

The suspicious thing about this was that it only gave problems with your RTO plugin but does not generate problems with 2 other alternative plugins that I was testing with. 

I wanted to go back to yours as it is simpler to use. The update fixed it.

Thanks for the response (and the patience).

---

Warning: Undefined array key 0 in /home1/XXXXXXXXXXXX/public_html/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-url.php on line 34

Deprecated: preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /home1/XXXXXXXXXXXXX/public_html/wp-includes/kses.php on line 1735
