### ISSUE TITLE
i18n: move the German to translate.wordpress.org

### ISSUE THREAD

**Issue by ramiy** [RTO-Websites/dynamic-conditions#7]
The PO/MO files for the German translations should be moved to translate.wordpress.org

----

How to do this?

1. Visit: https://translate.wordpress.org/projects/wp-plugins/dynamicconditions/

2. Select the "German" language.

3. Select the "Development (trunk)" project.

4. Scroll to the footer and click the "Import Translations".

![gt](https://user-images.githubusercontent.com/576623/55691797-9e7fd180-59aa-11e9-8901-0fc0c1c9802a.png)

----

This will help you migrate all your translations the wp.org, making the plugin smaller. Also, this way when you need to update translation strings, you don't need to release new versions just use the translation platform and all the sites using the plugin will be update within 12 hours (when they activate the WP Cron that checks for translations).

**Comment by crazypsycho** [comment]
Hello,

you are right, we should do this. I think we will do it in a few days.

**Comment by ramiy** [comment]
@crazypsycho I can do it for you...

**Comment by crazypsycho** [comment]
Hello,

this would be very helpful, cause currently we have not enough time for this.
Very thanks in advance

**Comment by ramiy** [comment]
Done.

See here: https://translate.wordpress.org/projects/wp-plugins/dynamicconditions/dev/de/default/

**Comment by crazypsycho** [comment]
Very thanks for this. When it is approved, we will remove the language-files.
