### ISSUE TITLE
Custom Taxonomies not available for Number Posts

### ISSUE THREAD

**Issue by danedigi** [RTO-Websites/dynamic-conditions#72]
I noticed i'm not able to use my custom taxonomies for the "Number Posts" dynamic tag. I can select the custom post but the "Category" doesn't show nay of my custom taxonomies. 

![Screenshot 2023-12-26 at 16 32 53](https://github.com/RTO-Websites/dynamic-conditions/assets/129627660/18bc6317-6ab2-4cf7-a180-07e9e581775f)

For example, I have a "News" custom post type with a custom taxonomy that contains "Press Releases" and want to be able to hide a button based on the number of post in that taxonomy.

**Comment by crazypsycho** [comment]
I recommend to use https://de.wordpress.org/plugins/dynamictags/
This provides the NumberPostQuery-Tag, what should do what you want.
