### ISSUE TITLE
Feature Request: Hover reveal condition for content

### ISSUE THREAD

**Issue by MiMoHo** [RTO-Websites/dynamic-conditions#73]
I would like to use the Elementor plugin for framed content from another website like a Google Sheet. I don't wanna hide it entirely from visitors but only allow subscribers to access its content in full.
So what I wish to do is activate a "hover reveal" function for guests that can only see a tiny bit of the iFrame content that they hover over with the cursor or finger so that they can check that the content is there which makes a purchase much more trustworthy knowing the content exists for real and just needs to be unlocked.
Are you interested in implementing this functionality?

**Comment by crazypsycho** [comment]
This is a different use case which would require a different plugin. So sorry but its not planned.
