### ISSUE TITLE
PHP 8.2 incompatibility errors: Creation of dynamic property .... is deprecated messages

### ISSUE THREAD

**Issue by Chris--S** [RTO-Websites/dynamic-conditions#75]
Dynamic Conditions: 1.6.2
PHP: 8.2.15

Elementor: 3.21.4
Elementor Pro: 3.21.2
Wordpress 6.5.2

E.g. : Creation of dynamic property Elementor\Includes\Elements\Container::$dynamicConditionIsHidden is deprecated in
~/wp-content/plugins/dynamicconditions/Public/DynamicConditionsPublic.php
on line
325

: Creation of dynamic property Elementor\Includes\Elements\Container::$dynamicConditionSettings is deprecated in
~/wp-content/plugins/dynamicconditions/Public/DynamicConditionsPublic.php
on line
326

**Comment by crazypsycho** [comment]
This is fixed with 1.6.3, thanks for report
