### ISSUE TITLE
Last update broke WP

### ISSUE THREAD

**Issue by danielporto** [RTO-Websites/dynamic-conditions#8]
Hey guys, last update took my website down.
Here is the error message:

Error Details
=============
An error of type E_PARSE was caused in line 145 of the file /home/XXXXXX/public_html/yyyyyyy/wp-content/plugins/dynamicconditions/public/DynamicConditionsPublic.php. Error message: syntax error, unexpected ':', expecting ';' or '{'

edit: context:
Wordpress 5.2 with Elementor pro and a few other plugins.

**Comment by crazypsycho** [comment]
Hello,

i think you have an older php-version. I will made a fix, sorry for that.

**Comment by danielporto** [comment]
Thanks for the quick reply. I will contact my provider about that. Thanks.

**Comment by Enoray** [comment]
Issue should be fixed.
