### ISSUE TITLE
Repeater True/False not working

### ISSUE THREAD

**Issue by tstokes8040** [RTO-Websites/dynamic-conditions#82]
When choosing The ACF Repeater True/False option, and then selecting the True/False field, I set the True Message to “Yes” and the False Message to “No”. I then compare via text to only show when the value is “Yes” meaning true. This has stopped working and is always giving the false value. https://share.zight.com/4guGD911

**Comment by tstokes8040** [comment]
@shennemann-rto any ideas here?

**Comment by crazypsycho** [comment]
I´m not sure which dynamic-tag do you use. `ae-boolean` seems not to be the tag from elementor.
When i use the ACF-Repeater-Tag from elementor itself and than select a boolean-field, i have a comma-seperated list with the options like "no,yes,no".

**Comment by tstokes8040** [comment]
@crazypsycho I have an AE Template. This template gets pulled in from the Elementor `AE - ACF Repeater` element. On the AE template, I have a bunch of fields. I use Dynamic conditions to hide/show based on a boolean condition. The dynamic tag being used is `(AE) ACF Repeater Boolean` here are my settings for that (https://share.zight.com/geuKZr5b). Then here is the rest of the configuration (https://share.zight.com/v1uqlr1r). This used to work. A fairly recent update caused this to break.

**Comment by crazypsycho** [comment]
I´m not sure what AE is. I only found Anywhere Elementor, but it seems that this doesnt provide an AE-ACF-Repeater-Tag.
Maybe you can use the elementor-build-in ACF-Repeater-Tag to do what you want?

**Comment by tstokes8040** [comment]
@crazypsycho Yep it is Anywhere Elementor. Im not sure I know where the built in ACF Repeater tag is?

**Comment by crazypsycho** [comment]
Should be here:
![grafik](https://github.com/user-attachments/assets/b2be2a31-959d-4369-876b-dc0f8fc43428)

**Comment by crazypsycho** [comment]
Sorry, my mistake. The tag is not built-in. It´s only in my test-installation in an other plugin and developed by me years ago but never published.

But dynamicconditions only reads what the tag spits out. So I think the issue could be in the tag itself.
Did it output the correct value if you use this tag as content for a text-widget?
If not, than you have to find out which plugin delievers the tag and ask the developers for fixing.

**Comment by tstokes8040** [comment]
I worked this out with the Anywhere Elementor team. They helped me get setup with their conditions.
